### ISSUE TITLE
My 2 pence

### ISSUE THREAD

**Issue by ghost** [cybermaggedon/gnucash-uk-vat#2]
Some time ago I started on the self employed part of MTD, then gave up.  It's at https://github.com/EvansMike/hmrc_self_submit if any of that code is useful, if it's still compatible with the API , then please use it for integration into GnuCash. I don't pay VAT so I never got into the VAT part.

**Comment by cybermaggedon** [comment]
@ac000 same here. I've been submitting my own VAT returns. I would be happy to share a few credentials 1-to-1 but there's a limit to how many can be generated. Supposedly other people could apply for credentials for this code for themselves. I'm guessing that if they referenced my own application, they would be able to get credentials without having to go through all the steps I went through,

**Comment by ac000** [comment]
> Supposedly other people could apply for credentials for this code for themselves.

That's what I was originally told also.

However when it came to the live demo, fairly early on they saw me copy and pasting the credentials 'into the app' as part of its initial set up. They immediately got concerned that they were somehow public. Once I'd explained to them that, no, they are only stored locally, they then questioned how this would work for other people using the app.

At that point a I explained that I had been told what we were both told, that other users would need to apply for credentials themselves, to which they said that was impractical and that was the end of the demo. They asked for a copy of the email where I'd been told about other users applying for credentials. 

Got a quick response back saying they were going to look through everything.

Then about a month later after pinging them a couple of times

> I really do apologise about the time this is taking but we are having to have discussions with colleagues in all different areas, especially policy, regarding your application. The difficulty in delivering a message is the fact that your product is an in house product.

It's been two months since I last had a response from them, time to turn up the heat a little I think...

**Comment by cybermaggedon** [comment]
@ac000 sorry to hear it, I didn't have that experience. I got the approval for live credentials, and then we talked about whether credentials could be shared in open source or not (answer: No). The whole thing was turned around in under 2 weeks IIRC.

If I understand, "In-house product" has a specific meaning.  At one point in the dialogue I was offered two paths:
> Questionnaire 1 applies if you plan to sell/license your product
> Questionnaire 2 applies if your product is to be used as an In-house solution only

In-house refers to a product developed internally within your org, and only used by your org.  I applied for sell/license.  Maybe check you were sent the right questionnaire.

**Comment by ac000** [comment]
Ah, that's useful information, thanks!

I remember reading about a questionnaire on the HMRC site, but I never actually filled one in, there was juts a bit of back and forth over email and then the demo.

Thanks, this information will help me formulate a new email to them...
